from typing import TypedDict, List


class CustomerSupportState(TypedDict):
    # Customer Information
    customer_name: str

    # Current customer query
    query: str

    # Detected intent
    intent: str

    # Support department
    department: str

    # Retrieved RAG context
    retrieved_docs: List[str]

    # Draft response generated by agent
    draft_response: str

    # Human approval required?
    requires_approval: bool

    # Human approval status
    approved: bool

    # Final response after supervisor review
    final_response: str

    # Conversation history
    conversation_history: List[str]